#!/usr/bin/env php
<?php
/**
 * Cubex Console Application
 */
//Defining PHP_START will allow cubex to add an execution time header
define('PHP_START', microtime(true));

//Include the composer autoloader
require_once __DIR__ . '/vendor/autoload.php';

//Create an instance of cubex, with the bin root defined
$app = new \Cubex\Cubex(__DIR__ . DIRECTORY_SEPARATOR . 'public/');

//Boot Cubex
$app->boot();

//Create a request object
$request = \Cubex\Http\Request::createConsoleRequest();
$app->instance('request', $request);

//Create a new console application
$console = \Cubex\Console\Console::withCubex($app);

//Execute the command and retrieve the exit code
$exit = $console->run();

$app->shutdown();

exit($exit);
